database:
  mysql:
    host: MYSQL_HOST
    port: MYSQL_PORT
    user: MYSQL_USER
    password: MYSQL_PASSWORD
    database: MYSQL_DB
jwt:
  secret: JWT_SECRET
aws:
  accessKeyId: AWS_ACCESS_KEY_ID
  secretAccessKey: AWS_SECRET_ACCESS_KEY
  region: AWS_REGION
  bucket: AWS_S3_BUCKET
  agoraBucket: AWS_S3_AGORA_BUCKET
fcm:
  projectId: FIREBASE_PROJECT_ID
  serverKey: FCM_SERVER_KEY
agora:
  appId: AGORA_APP_ID
  appCertificate: AGORA_APP_CERTIFICATE
  apiKey: AGORA_API_KEY
  apiSecret: AGORA_API_SECRET
smsbox:
  apiKey: SMSBOX_API_KEY
